using IP3Project.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IP3Project.Controllers
{
    /// <summary>
    /// Abstract base controller that all controllers will inherit from
    /// </summary>
    public abstract class BaseController : Controller
    {
        public IdeagenAPI API = new IdeagenAPI(); //initilize global API wrapper 

        /// <summary>
        /// ERROR HANDLING AUTO GENERATED BY MVC
        /// </summary>
        /// <returns>VIEW WITH ERRORS</returns>
        public IActionResult APIError()
        {
            ViewData["message"] = "This error was generated on communicating with the API. Please contact your system support.";
            return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}
