using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IP3Project.Models;
using RestSharp;
using Newtonsoft.Json;

namespace IP3Project.Controllers
{
    public class HomeController : BaseController
    {
        /// <summary>
        /// Displays the Index Page with a list of all Timelines
        /// Calls GetAllTimelines function to populate the viewmodel with Timelines
        /// </summary>
        /// <returns>View with a TimLineList viewmodel</returns>
        public IActionResult Index()
        {
            TimelineList model = new TimelineList(); // Initilises a new TimeLineList view model
            model = GetAllTimelines(model); //Calls the GetAllTimelines utility Function

            return View(model); //returns view with model
        }



        /// <summary>
        /// Deletes a Timeline from the API and returns to the list of timelines
        /// </summary>
        /// <param name="Id">String Id of timeline to be deleted</param>
        /// <returns>Redirects to Index Action</returns>
        public IActionResult Delete(string Id)
        {

            string IsSuccessful = DeleteTimeline(Id); //Calls delete timeline method which will give a success or failure string

            return RedirectToAction("Index"); //returns to the Index!

        }

        /// <summary>
        /// ERROR HANDLING AUTO GENERATED BY MVC
        /// </summary>
        /// <returns>VIEW WITH ERRORS</returns>
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
        #region Utility

        /// <summary>
        /// Makes a request to the API and returns a populated view model with all timelines 
        /// </summary>
        /// <param name="model">TimelineList viewmodel to be populated with a list of timelines</param>
        /// <returns>Populated TimelineList viewmodel</returns>
        private TimelineList GetAllTimelines(TimelineList model)
        {

            var request = new RestRequest("Timeline/GetTimelines"); //setting up the request params
            IRestResponse response = API.GetRequest(request); //Uses IdeagenAPI wrapperclass to make a request and retreives the response

            var resultsDTO = JsonConvert.DeserializeObject<List<Timeline>>(response.Content); //Deserializes the results from the response

            //Populates the viewmodel with relevent results
            foreach (Timeline x in resultsDTO)
            {
                model.timelines.Add(new TimelineViewModel(x.Title, x.CreationTimeStamp, x.Id));
            }

            return model;
        }

        /// <summary>
        /// Deletes a timeline by making a request to the api and returns a sucess string
        /// </summary>
        /// <param name="Id">String Id of object to be deleted</param>
        /// <returns>Sucess string</returns>
        private string DeleteTimeline(string Id)
        {

            var request = new RestRequest("Timeline/Delete"); //setting up the request params

            DeleteViewModel DeleteModel = new DeleteViewModel(); //Creates a delete view model to help handle request

            DeleteModel.TimelineId = Id; //Sets the ID of the timeline to be deleted
             
            var success = API.PutRequest(request, DeleteModel); //Calls API to do request and gets response content from it

            return success.ToString();

        }

        #endregion


    }
}
